#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-cliapp
Version  : 1.20150305.orig
Release  : 3
URL      : http://code.liw.fi/debian/pool/main/p/python-cliapp/python-cliapp_1.20150305.orig.tar.gz
Source0  : http://code.liw.fi/debian/pool/main/p/python-cliapp/python-cliapp_1.20150305.orig.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: python-cliapp-python
Requires: python-cliapp-doc
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
=================
cliapp is a Python framework for Unix-like command line programs.
The scaffolding to set up a command line parser, open each input
file, read each line of input, etc, is the same in each program.
Only the logic of what to do with each line differs.

%package doc
Summary: doc components for the python-cliapp package.
Group: Documentation

%description doc
doc components for the python-cliapp package.


%package python
Summary: python components for the python-cliapp package.
Group: Default

%description python
python components for the python-cliapp package.


%prep
%setup -q -n cliapp-1.20150305

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man5/*

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
